const popupModalActionTypes = {
    CLOSE_POPUP_MODAL: 'CLOSE_POPUP_MODAL',
    OPEN_ACC_SETTING_MODAL: 'OPEN_ACC_SETTING_MODAL',
    OPEN_CHANGE_PASSWORD_MODAL: 'OPEN_CHANGE_PASSWORD_MODAL',
};

export default popupModalActionTypes;
