const userActionTypes = {
    // authentication
    IS_USER_LOGGED_IN: 'IS_USER_LOGGED_IN',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    // user settings
    UPDATE_SETTINGS_START: 'UPDATE_SETTINGS_START',
    UPDATE_SETTINGS_SUCCESS: 'UPDATE_SETTINGS_SUCCESS',
    UPDATE_SETTINGS_FAILURE: 'UPDATE_SETTINGS_FAILURE',
    CHANGE_PASSWORD_START: 'CHANGE_PASSWORD_START',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',

    // clear user error
    CLEAR_USER_ERROR_MESSAGE: 'CLEAR_USER_ERROR_MESSAGE',
};

export default userActionTypes;
